services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: pixelart-sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - pixelart-sqldata:/var/opt/mssql
    restart: unless-stopped

volumes:
  pixelart-sqldata:
